### ISSUE TITLE
$validator->getData() array type

### ISSUE THREAD

**Issue by stefandanaita** [SUKOHI/CsvValidator#1]
Hey. Can you please make the validator according to the Laravel one and return an associative array when $validator->getData() is called? I am using the rules with keys instead of indexes and the getData() method returns indexes, not keys.

**Comment by SUKOHI** [comment]
Hi, stefandanaita!
Thank you for your message.

Unfortunately, this package doesn't support what you want so far.
Sorry that I can't live up to your expectations.
